* Warfare
/A library for creating Discord Bots in Common Lisp./

** WARNING
Warfare is /extremely new/. It's currently in development, and just
barely getting its footing. The current goal is to get basic HTTP
interactions going, and then be able to establish a connection to, and
subsequently communicate over, the Gateway.

** LICENSE
Copyright © 2022 Alexander "Doctor Bluefall" Bisono.

Warfare is free software: you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Warfare is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public
License along with Warfare. If not, see
<https://www.gnu.org/licenses/>.
